# SCOPE Position Feature EDA Final

This notebook measures where content structures appear in cleaned main-page content and evaluates whether those measurements are ready for later econometric modeling.

**Boundary:** descriptive associations among sources already surfaced in the audit. This notebook does not fit a new LPM or logistic regression, does not use answer text or ranking variables, and makes no causal claim.

In [1]:
from pathlib import Path
import sys
import pandas as pd
import plotly.express as px
from IPython.display import display, HTML

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.econometrics_eda_v2.position_feature_eda import run_position_feature_eda

OUT = ROOT / 'outputs/position_feature_eda_final_20260731'
result = run_position_feature_eda(output_dir=OUT)
result

{'status': 'position_feature_eda_ready_for_model_planning',
 'version': 'position_feature_eda_v1_20260731',
 'rows': 5758,
 'unique_urls': 2881,
 'domains': 586,
 'citation_rate': 0.3287599861062869,
 'new_regression_estimated': False,
 'output_dir': '/Volumes/ExtremeSD/Metier/Research/CiteScope-content-audit/outputs/position_feature_eda_final_20260731',
 'static_report': '/Volumes/ExtremeSD/Metier/Research/CiteScope-content-audit/outputs/position_feature_eda_final_20260731/frontend/position_feature_eda_report.html',
 'all_validation_checks_passed': True}

## 1. Sample and extraction status

The row-level estimand remains citation conditional on a source being surfaced. URL-level coverage is reported separately so repeated source appearances are not described as additional webpages.

In [2]:
rows = pd.read_parquet(OUT / 'data/scope_condo_eda_ready_with_position_features.parquet')
coverage = pd.read_csv(OUT / 'tables/position_feature_coverage.csv')
missingness = pd.read_csv(OUT / 'tables/position_feature_missingness.csv')
sample_summary = pd.DataFrame([{
    'surfaced_rows': len(rows),
    'unique_urls': rows.normalized_url.nunique(),
    'unique_domains': rows.source_root_domain.nunique(),
    'unique_prompts': rows.prompt_id.nunique(),
    'citation_rate': rows.cited.mean(),
}])
display(sample_summary)
display(missingness)

   surfaced_rows  unique_urls  unique_domains  unique_prompts  citation_rate
0           5758         2881             586             498        0.32876

  position_extraction_status  pages  domains  page_share
0  main_content_parse_failed    111       35    0.038528
1                   measured   2770      565    0.961472

## 2. Feature audit and coverage

Baseline features are not automatically repeated. The audit distinguishes previously available variables from genuinely new position, intensity, density, and interaction measurements.

In [3]:
audit = pd.read_csv(OUT / 'tables/position_feature_audit.csv')
display(audit)
fig = px.bar(
    coverage.sort_values('percentage_of_eligible_pages'),
    x='percentage_of_eligible_pages', y='feature', orientation='h',
    text='pages_with_feature',
    title=f'Feature coverage among eligible pages (n={int(coverage.applicable_page_count.max()):,})',
)
fig.update_xaxes(tickformat='.0%')
fig.show()
display(coverage)

,feature_name,feature_group,feature_definition,already_exists,previously_analyzed,needs_extraction,newly_extracted,include_in_new_eda,reason,extraction_success_rate,missing_rate,applicable_page_count,applicable_domain_count,percentage_of_eligible_pages,fixed_effect_readiness
0,has_direct_answer,answerability_presence,At least one conservative direct-answer phrase...,False,False,True,True,True,New position/intensity measure or required pre...,0.961472,0.038528,2770.0,565.0,0.031408,Weak within-domain variation
1,has_question_heading,answerability_presence,Has question heading.,False,False,True,True,False,Registry concept not extracted in this version...,0.961472,0.038528,2770.0,565.0,0.196029,Ready
2,has_definition_block,answerability_presence,At least one definition list or explicit defin...,False,False,True,True,True,New position/intensity measure or required pre...,0.961472,0.038528,2770.0,565.0,0.409747,Ready
3,has_faq,answerability_presence,Visible FAQ heading/structure or FAQPage marku...,False,False,True,True,True,New position/intensity measure or required pre...,0.961472,0.038528,2770.0,565.0,0.133213,Ready
4,direct_answer_count,answerability_intensity,Direct answer count.,False,False,True,True,True,New position/intensity measure or required pre...,0.961472,0.038528,2770.0,565.0,0.031408,Weak within-domain variation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,domain,taxonomy_control,Domain.,False,False,False,False,False,"Existing identifier, denominator, grouping var...",NaN,NaN,NaN,NaN,NaN,NaN
95,prompt_id,taxonomy_control,Prompt id.,True,False,False,False,False,"Existing identifier, denominator, grouping var...",NaN,NaN,NaN,NaN,NaN,NaN
96,page_id,taxonomy_control,Page id.,False,False,True,True,False,"Existing identifier, denominator, grouping var...",NaN,NaN,NaN,NaN,NaN,NaN
97,word_count,taxonomy_control,Word count.,True,False,False,False,False,"Existing identifier, denominator, grouping var...",NaN,NaN,NaN,NaN,NaN,NaN
98,heading_count,taxonomy_control,Heading count.,True,False,False,False,False,"Existing identifier, denominator, grouping var...",NaN,NaN,NaN,NaN,NaN,NaN

,feature,presence_feature,already_present_in_source_data,newly_extracted,extraction_success_rate,missing_rate,applicable_page_count,pages_with_feature,percentage_of_eligible_pages,applicable_domain_count,domains_with_feature,page_types_with_feature,citation_rate_when_present,citation_rate_when_absent,reason
0,table,has_table,True,False,0.961472,0.038528,2770,438,0.158123,565,106,11,0.338446,0.320930,Position-bearing feature included in new EDA.
1,list,has_bullets,False,True,0.961472,0.038528,2770,1292,0.466426,565,260,12,0.300394,0.344396,Position-bearing feature included in new EDA.
2,faq,has_faq,False,True,0.961472,0.038528,2770,369,0.133213,565,86,9,0.314322,0.325680,Position-bearing feature included in new EDA.
3,direct_answer,has_direct_answer,False,True,0.961472,0.038528,2770,87,0.031408,565,27,5,0.420168,0.319696,Position-bearing feature included in new EDA.
4,definition,has_definition_block,False,True,0.961472,0.038528,2770,1135,0.409747,565,284,12,0.350570,0.302601,Position-bearing feature included in new EDA.
5,comparison,has_comparison,False,True,0.961472,0.038528,2770,570,0.205776,565,152,11,0.370532,0.308588,Position-bearing feature included in new EDA.
6,steps,has_steps,False,True,0.961472,0.038528,2770,387,0.139711,565,163,10,0.351259,0.318900,Position-bearing feature included in new EDA.
7,numeric_evidence,has_numeric_evidence,False,True,0.961472,0.038528,2770,1426,0.514801,565,286,13,0.299964,0.348854,Position-bearing feature included in new EDA.
8,external_citation,has_external_sources,False,True,0.961472,0.038528,2770,826,0.298195,565,202,12,0.320513,0.325655,Position-bearing feature included in new EDA.
9,question_heading,has_question_heading,False,True,0.961472,0.038528,2770,543,0.196029,565,153,11,0.351938,0.315489,Position-bearing feature included in new EDA.

## 3. Position distributions and citation rates

`No feature` is distinct from Q1. Position zero means the feature begins at the start of main content. Continuous comparisons are conditional on the feature being present.

In [4]:
distribution = pd.read_csv(OUT / 'tables/position_feature_distribution_summary.csv')
citation = pd.read_csv(OUT / 'tables/citation_rate_by_feature_position.csv')
display(distribution)

for feature in ['table', 'faq', 'direct_answer', 'definition', 'comparison']:
    chart = citation[
        citation.feature.eq(feature)
        & citation.grouping.eq('quartile')
        & citation.sample_scope.eq('full_sample')
    ].sort_values('category_order')
    fig = px.bar(
        chart, x='category', y='citation_rate', text='n_observations',
        error_y=chart.ci_high - chart.citation_rate,
        error_y_minus=chart.citation_rate - chart.ci_low,
        title=f'Citation rate by {feature.replace("_", " ")} position (n={int(chart.n_observations.sum()):,})',
    )
    fig.update_yaxes(tickformat='.0%')
    fig.show()

,feature,position_feature,n_present_rows,n_present_pages,median_position_ratio,q1_position_ratio,q3_position_ratio,mean_position_ratio,minimum_position_ratio,maximum_position_ratio
0,table,first_table_position_ratio,978,438,0.137752,0.051864,0.323171,0.230561,0.0,0.960086
1,list,first_list_position_ratio,2540,1292,0.176707,0.041926,0.445638,0.277511,0.0,0.993103
2,faq,faq_start_position_ratio,789,369,0.793984,0.678922,0.920000,0.751667,0.0,0.985106
3,direct_answer,direct_answer_position_ratio,238,87,0.721931,0.558824,0.738347,0.612398,0.0,0.993815
4,definition,first_definition_position_ratio,2456,1135,0.086528,0.026853,0.273088,0.200744,0.0,0.998427
5,comparison,first_comparison_position_ratio,1371,570,0.327660,0.123581,0.642544,0.393907,0.0,0.988617
6,steps,first_steps_position_ratio,874,387,0.371814,0.105079,0.669425,0.412225,0.0,0.998313
7,numeric_evidence,first_numeric_evidence_position_ratio,2787,1426,0.085496,0.024390,0.238197,0.169923,0.0,0.981781
8,external_citation,first_external_citation_position_ratio,1716,826,0.388485,0.120968,0.881745,0.475039,0.0,0.999404
9,question_heading,first_question_heading_position_ratio,1290,543,0.474194,0.110942,0.860043,0.481772,0.0,0.994032

## 4. Cited versus not-cited positions

Means and medians below use only pages containing the relevant feature. Skewed position distributions make medians especially important.

In [5]:
outcome = pd.read_csv(OUT / 'tables/position_feature_outcome_comparison.csv')
display(outcome)

,feature,position_feature,cited_mean,not_cited_mean,cited_median,not_cited_median,difference_in_means,difference_in_medians,cited_n,not_cited_n
0,table,first_table_position_ratio,0.268239,0.211285,0.178317,0.113833,0.056954,0.064484,331,647
1,list,first_list_position_ratio,0.291390,0.271552,0.216438,0.149254,0.019838,0.067185,763,1777
2,faq,faq_start_position_ratio,0.766356,0.744933,0.817593,0.790698,0.021422,0.026895,248,541
3,direct_answer,direct_answer_position_ratio,0.584160,0.632860,0.721030,0.722411,-0.048700,-0.001381,100,138
4,definition,first_definition_position_ratio,0.181119,0.211338,0.084135,0.087576,-0.030219,-0.003442,861,1595
5,comparison,first_comparison_position_ratio,0.413766,0.382218,0.363221,0.322344,0.031548,0.040877,508,863
6,steps,first_steps_position_ratio,0.430134,0.402529,0.386473,0.368559,0.027605,0.017914,307,567
7,numeric_evidence,first_numeric_evidence_position_ratio,0.180991,0.165181,0.084440,0.086747,0.015810,-0.002307,836,1951
8,external_citation,first_external_citation_position_ratio,0.478955,0.473191,0.402687,0.351703,0.005764,0.050984,550,1166
9,question_heading,first_question_heading_position_ratio,0.456231,0.495642,0.416037,0.512131,-0.039411,-0.096093,454,836

## 5. Domain fixed-effect readiness

Readiness requires position variation and citation-outcome variation within the same domains. The thresholds are documented in the table and are planning rules, not statistical significance tests.

In [6]:
within = pd.read_csv(OUT / 'tables/position_feature_within_domain_diagnostics.csv')
fig = px.scatter(
    within, x='within_domain_standard_deviation',
    y='domains_with_both_position_and_outcome_variation',
    size='informative_observations', color='fixed_effect_readiness',
    hover_name='feature', title=f'Domain fixed-effect readiness (n={len(rows):,} surfaced rows)',
)
fig.show()
display(within)

,feature,position_feature,total_domains,domains_with_at_least_two_pages,domains_containing_feature,domains_with_presence_variation,domains_with_position_ratio_variation,domains_with_position_quartile_variation,domains_with_citation_outcome_variation,domains_with_both_position_and_outcome_variation,informative_observations,share_of_singleton_domains,overall_standard_deviation,between_domain_standard_deviation,within_domain_standard_deviation,within_domain_sd_near_zero,fixed_effect_readiness,readiness_threshold
0,table,first_table_position_ratio,586,244,106,44,38,15,210,33,829,0.583618,0.236159,0.271036,0.114681,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
1,list,first_list_position_ratio,586,244,260,70,106,68,210,83,2130,0.583618,0.276465,0.256706,0.171757,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
2,faq,faq_start_position_ratio,586,244,86,31,40,21,210,32,609,0.583618,0.214860,0.194058,0.146857,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
3,direct_answer,direct_answer_position_ratio,586,244,27,17,7,3,210,7,205,0.583618,0.290373,0.278444,0.075662,False,Weak within-domain variation,"Ready: >=30 domains, >=300 rows, within SD >=0..."
4,definition,first_definition_position_ratio,586,244,284,81,114,64,210,93,2005,0.583618,0.258363,0.223710,0.154546,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
5,comparison,first_comparison_position_ratio,586,244,152,72,63,43,210,56,1183,0.583618,0.305311,0.254347,0.226375,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
6,steps,first_steps_position_ratio,586,244,163,92,54,37,210,46,639,0.583618,0.316946,0.286039,0.201874,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
7,numeric_evidence,first_numeric_evidence_position_ratio,586,244,286,91,119,72,210,89,2345,0.583618,0.208289,0.232511,0.141039,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
8,external_citation,first_external_citation_position_ratio,586,244,202,78,91,55,210,74,1434,0.583618,0.374178,0.350349,0.236185,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."
9,question_heading,first_question_heading_position_ratio,586,244,153,61,64,44,210,53,1042,0.583618,0.371331,0.303622,0.254059,False,Ready,"Ready: >=30 domains, >=300 rows, within SD >=0..."

## 6. Sparse cells, taxonomy confounding, and page length

Four quartiles are retained only when observed cells support them. Taxonomy cross-tabs use normalized percentages. Relative and absolute positions are compared with page length because the same token index can imply a different relative location on short and long pages.

In [7]:
sparse = pd.read_csv(OUT / 'tables/position_feature_sparse_cell_diagnostics.csv')
taxonomy = pd.read_csv(OUT / 'tables/position_feature_taxonomy_crosstab.csv')
page_length = pd.read_csv(OUT / 'tables/position_feature_page_length_relationship.csv')
display(sparse)
display(taxonomy.head(50))
display(page_length)

,category,n_observations,n_unique_pages,cited_count,not_cited_count,citation_rate,ci_low,ci_high,feature,position_feature,grouping,sample_scope,overall_citation_rate,citation_rate_difference,category_order,sparse_n_lt_20,sparse_cited_lt_5,sparse_not_cited_lt_5,sparse_flag,recommended_grouping
0,No feature,4515,2332,1449,3066,0.320930,0.307470,0.334695,table,first_table_position_ratio,quartile,full_sample,0.32876,-0.007830,0,False,False,False,False,"Q1, Q2, Q3, Q4"
1,Q1,622,309,186,436,0.299035,0.264378,0.336160,table,first_table_position_ratio,quartile,full_sample,0.32876,-0.029725,1,False,False,False,False,"Q1, Q2, Q3, Q4"
2,Q2,207,78,84,123,0.405797,0.341210,0.473817,table,first_table_position_ratio,quartile,full_sample,0.32876,0.077037,2,False,False,False,False,"Q1, Q2, Q3, Q4"
3,Q3,119,37,54,65,0.453782,0.367175,0.543279,table,first_table_position_ratio,quartile,full_sample,0.32876,0.125022,3,False,False,False,False,"Q1, Q2, Q3, Q4"
4,Q4,30,14,7,23,0.233333,0.117924,0.409283,table,first_table_position_ratio,quartile,full_sample,0.32876,-0.095427,4,False,False,False,False,"Q1, Q2, Q3, Q4"
5,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,table,first_table_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
6,No feature,2953,1478,1017,1936,0.344396,0.327469,0.361726,list,first_list_position_ratio,quartile,full_sample,0.32876,0.015636,0,False,False,False,False,"Q1, Q2, Q3, Q4"
7,Q1,1458,756,413,1045,0.283265,0.260729,0.306939,list,first_list_position_ratio,quartile,full_sample,0.32876,-0.045495,1,False,False,False,False,"Q1, Q2, Q3, Q4"
8,Q2,526,247,183,343,0.347909,0.308440,0.389583,list,first_list_position_ratio,quartile,full_sample,0.32876,0.019149,2,False,False,False,False,"Q1, Q2, Q3, Q4"
9,Q3,336,169,107,229,0.318452,0.270931,0.370078,list,first_list_position_ratio,quartile,full_sample,0.32876,-0.010308,3,False,False,False,False,"Q1, Q2, Q3, Q4"
10,Q4,220,120,60,160,0.272727,0.218154,0.335101,list,first_list_position_ratio,quartile,full_sample,0.32876,-0.056033,4,False,False,False,False,"Q1, Q2, Q3, Q4"
11,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,list,first_list_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
12,No feature,4704,2401,1532,3172,0.325680,0.312435,0.339210,faq,faq_start_position_ratio,quartile,full_sample,0.32876,-0.003080,0,False,False,False,False,"Q1, Q2, Q3, Q4"
13,Q1,29,14,9,20,0.310345,0.172756,0.492301,faq,faq_start_position_ratio,quartile,full_sample,0.32876,-0.018415,1,False,False,False,False,"Q1, Q2, Q3, Q4"
14,Q2,77,45,24,53,0.311688,0.219273,0.422000,faq,faq_start_position_ratio,quartile,full_sample,0.32876,-0.017072,2,False,False,False,False,"Q1, Q2, Q3, Q4"
15,Q3,177,79,43,134,0.242938,0.185656,0.311141,faq,faq_start_position_ratio,quartile,full_sample,0.32876,-0.085822,3,False,False,False,False,"Q1, Q2, Q3, Q4"
16,Q4,506,231,172,334,0.339921,0.299993,0.382261,faq,faq_start_position_ratio,quartile,full_sample,0.32876,0.011161,4,False,False,False,False,"Q1, Q2, Q3, Q4"
17,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,faq,faq_start_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
18,No feature,5255,2683,1680,3575,0.319696,0.307222,0.332432,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,-0.009064,0,False,False,False,False,"First quartile, middle half, last quartile"
19,Q1,41,16,21,20,0.512195,0.364845,0.657456,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,0.183435,1,False,False,False,False,"First quartile, middle half, last quartile"
20,Q2,13,7,4,9,0.307692,0.126807,0.576307,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,-0.021068,2,True,True,False,True,"First quartile, middle half, last quartile"
21,Q3,141,46,61,80,0.432624,0.353706,0.515116,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,0.103864,3,False,False,False,False,"First quartile, middle half, last quartile"
22,Q4,43,18,14,29,0.325581,0.204933,0.474838,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,-0.003179,4,False,False,False,False,"First quartile, middle half, last quartile"
23,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,direct_answer,direct_answer_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"First quartile, middle half, last quartile"
24,No feature,3037,1635,919,2118,0.302601,0.286521,0.319180,definition,first_definition_position_ratio,quartile,full_sample,0.32876,-0.026159,0,False,False,False,False,"Q1, Q2, Q3, Q4"
25,Q1,1808,807,662,1146,0.366150,0.344250,0.388619,definition,first_definition_position_ratio,quartile,full_sample,0.32876,0.037390,1,False,False,False,False,"Q1, Q2, Q3, Q4"
26,Q2,313,158,103,210,0.329073,0.279366,0.382925,definition,first_definition_position_ratio,quartile,full_sample,0.32876,0.000313,2,False,False,False,False,"Q1, Q2, Q3, Q4"
27,Q3,152,80,46,106,0.302632,0.235206,0.379787,definition,first_definition_position_ratio,quartile,full_sample,0.32876,-0.026128,3,False,False,False,False,"Q1, Q2, Q3, Q4"
28,Q4,183,90,50,133,0.273224,0.213821,0.341952,definition,first_definition_position_ratio,quartile,full_sample,0.32876,-0.055536,4,False,False,False,False,"Q1, Q2, Q3, Q4"
29,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,definition,first_definition_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
30,No feature,4122,2200,1272,2850,0.308588,0.294671,0.322862,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,-0.020172,0,False,False,False,False,"Q1, Q2, Q3, Q4"
31,Q1,601,247,216,385,0.359401,0.322044,0.398544,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,0.030641,1,False,False,False,False,"Q1, Q2, Q3, Q4"
32,Q2,278,112,94,184,0.338129,0.285062,0.395610,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,0.009370,2,False,False,False,False,"Q1, Q2, Q3, Q4"
33,Q3,250,114,101,149,0.404000,0.345071,0.465835,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,0.075240,3,False,False,False,False,"Q1, Q2, Q3, Q4"
34,Q4,242,97,97,145,0.400826,0.341097,0.463655,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,0.072066,4,False,False,False,False,"Q1, Q2, Q3, Q4"
35,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,comparison,first_comparison_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
36,No feature,4619,2383,1473,3146,0.318900,0.305615,0.332486,steps,first_steps_position_ratio,quartile,full_sample,0.32876,-0.009860,0,False,False,False,False,"Q1, Q2, Q3, Q4"
37,Q1,354,175,114,240,0.322034,0.275494,0.372395,steps,first_steps_position_ratio,quartile,full_sample,0.32876,-0.006726,1,False,False,False,False,"Q1, Q2, Q3, Q4"
38,Q2,156,69,61,95,0.391026,0.317950,0.469339,steps,first_steps_position_ratio,quartile,full_sample,0.32876,0.062266,2,False,False,False,False,"Q1, Q2, Q3, Q4"
39,Q3,202,84,70,132,0.346535,0.284328,0.414470,steps,first_steps_position_ratio,quartile,full_sample,0.32876,0.017775,3,False,False,False,False,"Q1, Q2, Q3, Q4"
40,Q4,162,59,62,100,0.382716,0.311408,0.459457,steps,first_steps_position_ratio,quartile,full_sample,0.32876,0.053956,4,False,False,False,False,"Q1, Q2, Q3, Q4"
41,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,steps,first_steps_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
42,No feature,2706,1344,944,1762,0.348854,0.331123,0.367015,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,0.020094,0,False,False,False,False,"Q1, Q2, Q3, Q4"
43,Q1,2106,1086,610,1496,0.289649,0.270673,0.309391,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,-0.039111,1,False,False,False,False,"Q1, Q2, Q3, Q4"
44,Q2,415,197,141,274,0.339759,0.295846,0.386611,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,0.010999,2,False,False,False,False,"Q1, Q2, Q3, Q4"
45,Q3,187,100,52,135,0.278075,0.218817,0.346267,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,-0.050685,3,False,False,False,False,"Q1, Q2, Q3, Q4"
46,Q4,79,43,33,46,0.417722,0.315266,0.527807,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,0.088962,4,False,False,False,False,"Q1, Q2, Q3, Q4"
47,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,numeric_evidence,first_numeric_evidence_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
48,No feature,3777,1944,1230,2547,0.325655,0.310894,0.340771,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,-0.003105,0,False,False,False,False,"Q1, Q2, Q3, Q4"
49,Q1,712,372,223,489,0.313202,0.280214,0.348195,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,-0.015558,1,False,False,False,False,"Q1, Q2, Q3, Q4"
50,Q2,213,113,68,145,0.319249,0.260319,0.384583,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,-0.009511,2,False,False,False,False,"Q1, Q2, Q3, Q4"
51,Q3,171,75,62,109,0.362573,0.294270,0.436915,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,0.033813,3,False,False,False,False,"Q1, Q2, Q3, Q4"
52,Q4,620,266,197,423,0.317742,0.282311,0.355418,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,-0.011018,4,False,False,False,False,"Q1, Q2, Q3, Q4"
53,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,external_citation,first_external_citation_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"
54,No feature,4203,2227,1326,2877,0.315489,0.301614,0.329701,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,-0.013271,0,False,False,False,False,"Q1, Q2, Q3, Q4"
55,Q1,532,186,205,327,0.385338,0.344945,0.427375,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,0.056578,1,False,False,False,False,"Q1, Q2, Q3, Q4"
56,Q2,128,83,44,84,0.343750,0.267102,0.429504,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,0.014990,2,False,False,False,False,"Q1, Q2, Q3, Q4"
57,Q3,171,92,50,121,0.292398,0.229382,0.364536,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,-0.036362,3,False,False,False,False,"Q1, Q2, Q3, Q4"
58,Q4,459,182,155,304,0.337691,0.295932,0.382143,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,0.008931,4,False,False,False,False,"Q1, Q2, Q3, Q4"
59,Unmeasured,265,111,113,152,0.426415,0.368340,0.486593,question_heading,first_question_heading_position_ratio,quartile,full_sample,0.32876,0.097655,6,False,False,False,False,"Q1, Q2, Q3, Q4"

,taxonomy_value,position_category,n_observations,cited_count,unique_pages,row_percent_within_position,row_percent_within_taxonomy,citation_rate,feature,taxonomy_dimension
0,commercial_product_or_service,Q1,69,17,46,0.110932,0.704082,0.246377,table,page_type
1,commercial_product_or_service,Q2,16,3,8,0.077295,0.163265,0.187500,table,page_type
2,commercial_product_or_service,Q3,13,3,7,0.109244,0.132653,0.230769,table,page_type
3,comparison_or_review,Q1,109,55,47,0.175241,0.534314,0.504587,table,page_type
4,comparison_or_review,Q2,89,42,25,0.429952,0.436275,0.471910,table,page_type
5,comparison_or_review,Q3,6,3,4,0.050420,0.029412,0.500000,table,page_type
6,contact_or_location,Q1,2,0,2,0.003215,0.500000,0.000000,table,page_type
7,contact_or_location,Q2,2,0,1,0.009662,0.500000,0.000000,table,page_type
8,directory_or_listing,Q1,268,57,163,0.430868,0.875817,0.212687,table,page_type
9,directory_or_listing,Q2,32,12,10,0.154589,0.104575,0.375000,table,page_type
10,directory_or_listing,Q3,1,0,1,0.008403,0.003268,0.000000,table,page_type
11,directory_or_listing,Q4,5,1,3,0.166667,0.016340,0.200000,table,page_type
12,informational_content,Q1,170,57,47,0.273312,0.488506,0.335294,table,page_type
13,informational_content,Q2,61,24,30,0.294686,0.175287,0.393443,table,page_type
14,informational_content,Q3,94,47,20,0.789916,0.270115,0.500000,table,page_type
15,informational_content,Q4,23,6,9,0.766667,0.066092,0.260870,table,page_type
16,landing_or_brand_page,Q2,7,3,4,0.033816,0.875000,0.428571,table,page_type
17,landing_or_brand_page,Q3,1,0,1,0.008403,0.125000,0.000000,table,page_type
18,news_or_press,Q4,2,0,2,0.066667,1.000000,0.000000,table,page_type
19,rare_other,Q1,1,0,1,0.001608,1.000000,0.000000,table,page_type
20,search_or_results,Q3,1,1,1,0.008403,1.000000,1.000000,table,page_type
21,support_or_help,Q1,1,0,1,0.001608,0.500000,0.000000,table,page_type
22,support_or_help,Q3,1,0,1,0.008403,0.500000,0.000000,table,page_type
23,unknown,Q1,2,0,2,0.003215,0.500000,0.000000,table,page_type
24,unknown,Q3,2,0,2,0.016807,0.500000,0.000000,table,page_type
25,blog_or_content_site,Q1,127,65,43,0.204180,0.679144,0.511811,table,source_type
26,blog_or_content_site,Q2,12,5,6,0.057971,0.064171,0.416667,table,source_type
27,blog_or_content_site,Q3,33,20,4,0.277311,0.176471,0.606061,table,source_type
28,blog_or_content_site,Q4,15,4,2,0.500000,0.080214,0.266667,table,source_type
29,directory_or_listing_platform,Q1,80,18,47,0.128617,0.672269,0.225000,table,source_type
30,directory_or_listing_platform,Q2,20,5,10,0.096618,0.168067,0.250000,table,source_type
31,directory_or_listing_platform,Q3,15,3,7,0.126050,0.126050,0.200000,table,source_type
32,directory_or_listing_platform,Q4,4,1,2,0.133333,0.033613,0.250000,table,source_type
33,government,Q1,3,2,2,0.004823,0.375000,0.666667,table,source_type
34,government,Q2,4,1,3,0.019324,0.500000,0.250000,table,source_type
35,government,Q3,1,0,1,0.008403,0.125000,0.000000,table,source_type
36,marketplace_or_platform,Q1,236,48,154,0.379421,0.848921,0.203390,table,source_type
37,marketplace_or_platform,Q2,25,17,7,0.120773,0.089928,0.680000,table,source_type
38,marketplace_or_platform,Q3,14,6,7,0.117647,0.050360,0.428571,table,source_type
39,marketplace_or_platform,Q4,3,0,2,0.100000,0.010791,0.000000,table,source_type
40,news_media,Q1,1,0,1,0.001608,0.333333,0.000000,table,source_type
41,news_media,Q4,2,0,2,0.066667,0.666667,0.000000,table,source_type
42,official_company_or_brand,Q1,142,45,49,0.228296,0.663551,0.316901,table,source_type
43,official_company_or_brand,Q2,34,4,19,0.164251,0.158879,0.117647,table,source_type
44,official_company_or_brand,Q3,34,13,15,0.285714,0.158879,0.382353,table,source_type
45,official_company_or_brand,Q4,4,0,4,0.133333,0.018692,0.000000,table,source_type
46,rare_other,Q1,1,0,1,0.001608,0.200000,0.000000,table,source_type
47,rare_other,Q2,2,1,2,0.009662,0.400000,0.500000,table,source_type
48,rare_other,Q4,2,2,2,0.066667,0.400000,1.000000,table,source_type
49,review_platform,Q1,32,8,12,0.051447,0.197531,0.250000,table,source_type

,feature,page_length_group,n_observations,n_unique_pages,median_word_count,median_position_ratio,median_absolute_token_position,citation_rate,dominant_position_quartile
0,table,Short,67,35,501.0,0.250000,39.0,0.223881,Q2
1,table,Medium,295,126,1084.0,0.264064,218.0,0.355932,Q1
2,table,Long,329,149,1756.0,0.099080,140.0,0.343465,Q1
3,table,Very long,287,128,3939.0,0.069906,246.0,0.341463,Q1
4,list,Short,286,172,570.5,0.326194,97.0,0.318182,Q1
5,list,Medium,684,259,1084.0,0.304491,230.0,0.406433,Q1
6,list,Long,712,403,1992.0,0.101950,141.0,0.248596,Q1
7,list,Very long,858,458,3725.0,0.088976,239.0,0.252914,Q1
8,faq,Short,78,38,500.0,0.738095,248.0,0.435897,Q4
9,faq,Medium,214,92,1084.0,0.791083,563.0,0.294393,Q4
10,faq,Long,272,116,1824.0,0.816299,1117.5,0.319853,Q4
11,faq,Very long,225,123,4074.0,0.801949,1934.0,0.284444,Q4
12,direct_answer,Short,18,8,683.5,0.655488,328.0,0.333333,Q3
13,direct_answer,Medium,126,44,1036.0,0.728916,667.0,0.420635,Q3
14,direct_answer,Long,74,23,2248.0,0.583607,351.5,0.472973,Q1
15,direct_answer,Very long,20,12,3374.0,0.672447,2977.0,0.300000,Q4
16,definition,Short,350,200,484.0,0.105183,35.5,0.368571,Q1
17,definition,Medium,757,280,1064.0,0.095778,75.0,0.392338,Q1
18,definition,Long,704,332,1837.5,0.062794,61.0,0.352273,Q1
19,definition,Very long,645,323,3595.0,0.106850,255.0,0.289922,Q1
20,comparison,Short,140,82,514.5,0.374607,122.0,0.335714,Q1
21,comparison,Medium,401,148,1064.0,0.399770,312.0,0.396509,Q1
22,comparison,Long,465,185,1824.0,0.303636,384.0,0.384946,Q1
23,comparison,Very long,365,155,3639.0,0.266092,742.0,0.336986,Q1
24,steps,Short,98,62,503.0,0.175305,40.5,0.244898,Q1
25,steps,Medium,277,97,994.0,0.393001,263.0,0.429603,Q1
26,steps,Long,278,116,1844.5,0.388718,483.0,0.352518,Q1
27,steps,Very long,221,112,3731.0,0.386473,1275.0,0.298643,Q2
28,numeric_evidence,Short,313,188,501.0,0.177474,52.0,0.258786,Q1
29,numeric_evidence,Medium,763,335,1050.0,0.124183,79.0,0.359109,Q1
30,numeric_evidence,Long,911,469,1907.0,0.077849,65.0,0.295280,Q1
31,numeric_evidence,Very long,800,434,3671.5,0.035913,73.0,0.265000,Q1
32,external_citation,Short,233,134,480.0,0.711688,147.0,0.317597,Q4
33,external_citation,Medium,488,196,1064.0,0.684250,348.5,0.350410,Q4
34,external_citation,Long,444,207,1992.0,0.191083,270.0,0.342342,Q1
35,external_citation,Very long,551,289,3831.0,0.241240,432.0,0.277677,Q1
36,question_heading,Short,138,80,543.5,0.490980,136.5,0.362319,Q4
37,question_heading,Medium,399,139,1063.0,0.598837,204.0,0.431078,Q1
38,question_heading,Long,352,162,1938.0,0.340493,422.0,0.323864,Q1
39,question_heading,Very long,401,162,4229.0,0.477183,1236.0,0.294264,Q4

## 7. Correlation and redundancy

Continuous measures use Spearman correlations. Binary presence indicators use phi correlations. Arbitrary category codes are never treated as continuous values.

In [8]:
associations = pd.read_csv(OUT / 'tables/position_feature_associations.csv')
high_pairs = pd.read_csv(OUT / 'tables/position_feature_high_correlation_pairs.csv')
categorical_associations = pd.read_csv(OUT / 'tables/position_feature_categorical_association.csv')
display(high_pairs)
for association_type in associations.association_type.unique():
    subset = associations[associations.association_type.eq(association_type)]
    pivot = subset.pivot(index='feature_a', columns='feature_b', values='association')
    px.imshow(
        pivot, zmin=-1, zmax=1, color_continuous_scale='RdBu_r', aspect='auto',
        title=f'{association_type.replace("_", " ").title()} association matrix',
    ).show()
display(categorical_associations)

,feature_a,feature_b,association,association_type,warning
0,direct_answer_position_ratio,first_numeric_evidence_position_ratio,-0.746126,spearman,High absolute Spearman correlation; avoid simu...
1,table_count,table_count_per_1000_words,0.996496,spearman,High absolute Spearman correlation; avoid simu...
2,list_count,list_item_density,0.938661,spearman,High absolute Spearman correlation; avoid simu...

,feature,position_category_feature,categorical_variable,association_type,association,n_pairwise_complete,warning
0,table,first_table_position_quartile,page_type,bias_corrected_cramers_v,0.159099,5758,NaN
1,table,first_table_position_quartile,source_type,bias_corrected_cramers_v,0.245160,5758,NaN
2,table,first_table_position_quartile,intent,bias_corrected_cramers_v,0.074185,5758,NaN
3,list,first_list_position_quartile,page_type,bias_corrected_cramers_v,0.174873,5758,NaN
4,list,first_list_position_quartile,source_type,bias_corrected_cramers_v,0.230248,5758,NaN
5,list,first_list_position_quartile,intent,bias_corrected_cramers_v,0.108447,5758,NaN
6,faq,faq_start_position_quartile,page_type,bias_corrected_cramers_v,0.124661,5758,NaN
7,faq,faq_start_position_quartile,source_type,bias_corrected_cramers_v,0.129132,5758,NaN
8,faq,faq_start_position_quartile,intent,bias_corrected_cramers_v,0.086736,5758,NaN
9,direct_answer,direct_answer_position_quartile,page_type,bias_corrected_cramers_v,0.162000,5758,NaN
10,direct_answer,direct_answer_position_quartile,source_type,bias_corrected_cramers_v,0.276107,5758,NaN
11,direct_answer,direct_answer_position_quartile,intent,bias_corrected_cramers_v,0.082330,5758,NaN
12,definition,first_definition_position_quartile,page_type,bias_corrected_cramers_v,0.169041,5758,NaN
13,definition,first_definition_position_quartile,source_type,bias_corrected_cramers_v,0.202389,5758,NaN
14,definition,first_definition_position_quartile,intent,bias_corrected_cramers_v,0.100338,5758,NaN
15,comparison,first_comparison_position_quartile,page_type,bias_corrected_cramers_v,0.161962,5758,NaN
16,comparison,first_comparison_position_quartile,source_type,bias_corrected_cramers_v,0.242451,5758,NaN
17,comparison,first_comparison_position_quartile,intent,bias_corrected_cramers_v,0.111488,5758,NaN
18,steps,first_steps_position_quartile,page_type,bias_corrected_cramers_v,0.123113,5758,NaN
19,steps,first_steps_position_quartile,source_type,bias_corrected_cramers_v,0.118930,5758,NaN
20,steps,first_steps_position_quartile,intent,bias_corrected_cramers_v,0.071210,5758,NaN
21,numeric_evidence,first_numeric_evidence_position_quartile,page_type,bias_corrected_cramers_v,0.178768,5758,NaN
22,numeric_evidence,first_numeric_evidence_position_quartile,source_type,bias_corrected_cramers_v,0.192381,5758,NaN
23,numeric_evidence,first_numeric_evidence_position_quartile,intent,bias_corrected_cramers_v,0.107778,5758,NaN
24,external_citation,first_external_citation_position_quartile,page_type,bias_corrected_cramers_v,0.160878,5758,NaN
25,external_citation,first_external_citation_position_quartile,source_type,bias_corrected_cramers_v,0.209183,5758,NaN
26,external_citation,first_external_citation_position_quartile,intent,bias_corrected_cramers_v,0.114530,5758,NaN
27,question_heading,first_question_heading_position_quartile,page_type,bias_corrected_cramers_v,0.183796,5758,NaN
28,question_heading,first_question_heading_position_quartile,source_type,bias_corrected_cramers_v,0.197945,5758,NaN
29,question_heading,first_question_heading_position_quartile,intent,bias_corrected_cramers_v,0.097028,5758,NaN

## 8. Manual stored-evidence QA and validation checks

The review sample contains 10 detected and 10 measured-negative pages for each major feature. It is based on stored cleaned HTML/Markdown; live-page drift remains possible.

In [9]:
manual = pd.read_csv(OUT / 'tables/position_feature_manual_validation.csv')
checks = pd.read_csv(OUT / 'tables/position_feature_validation_checks.csv')
display(manual.groupby(['feature', 'review_stratum', 'manual_validation_result']).size().reset_index(name='n'))
display(manual)
display(checks)
assert checks.passed.astype(bool).all()

         feature     review_stratum          manual_validation_result   n
0     comparison  detected_positive                     true_positive  10
1     comparison  measured_negative  true_negative_in_stored_snapshot  10
2     definition  detected_positive                     true_positive  10
3     definition  measured_negative  true_negative_in_stored_snapshot  10
4  direct_answer  detected_positive                     true_positive  10
5  direct_answer  measured_negative  true_negative_in_stored_snapshot  10
6            faq  detected_positive                     true_positive  10
7            faq  measured_negative  true_negative_in_stored_snapshot  10
8          table  detected_positive                     true_positive  10
9          table  measured_negative  true_negative_in_stored_snapshot  10

,feature,review_stratum,normalized_url,source_url,domain,detected_value,position_ratio,stored_evidence,manual_validation_result,review_note,validation_source
0,table,detected_positive,https://amazingproperties.org/search/bangkok/p...,https://amazingproperties.org/search/bangkok/p...,amazingproperties.org,1,0.581554,"[""Penthouse Segment Space Monthly Rental (THB)...",true_positive,Stored cleaned-main-content evidence visibly s...,stored_cleaned_main_content_html_or_markdown
1,table,detected_positive,https://apthai.com/th/blog/homestory/high-rise...,https://www.apthai.com/th/blog/homestory/high-...,apthai.com,1,0.050149,"[""รายชื่อคอนโด High Rise พื้นที่ใช้สอยและรถไฟฟ...",true_positive,Stored cleaned-main-content evidence visibly s...,stored_cleaned_main_content_html_or_markdown
2,table,detected_positive,https://asterofasia.com/blog/thailand-real-est...,https://asterofasia.com/blog/thailand-real-est...,asterofasia.com,1,0.497382,"[""Parameter Freehold Condo Leasehold Villa Via...",true_positive,Stored cleaned-main-content evidence visibly s...,stored_cleaned_main_content_html_or_markdown
3,table,detected_positive,https://avacasa.life/guides/bangkok-thonglor,https://avacasa.life/guides/bangkok-thonglor?u...,avacasa.life,1,0.287938,"[""Attraction Type Highlight Why It Matters Dis...",true_positive,Stored cleaned-main-content evidence visibly s...,stored_cleaned_main_content_html_or_markdown
4,table,detected_positive,https://baanlyy.com/areas/best-for/expats,https://baanlyy.com/areas/best-for/expats?utm_...,baanlyy.com,1,0.080581,"[""# Neighbourhood Expat-fit score Why it ranks...",true_positive,Stored cleaned-main-content evidence visibly s...,stored_cleaned_main_content_html_or_markdown
...,...,...,...,...,...,...,...,...,...,...,...
95,comparison,measured_negative,https://adamdecorcenter.com/vive-2,https://www.adamdecorcenter.com/vive-2/?utm_so...,adamdecorcenter.com,0,NaN,[],true_negative_in_stored_snapshot,No matching structure was found in the stored ...,stored_cleaned_main_content_html_or_markdown
96,comparison,measured_negative,https://insights.aecom.com/insights/article/lu...,https://insights.aecom.com/insights/article/lu...,aecom.com,0,NaN,[],true_negative_in_stored_snapshot,No matching structure was found in the stored ...,stored_cleaned_main_content_html_or_markdown
97,comparison,measured_negative,https://aestiqthonglor.com/,https://aestiqthonglor.com/?utm_source=chatgpt...,aestiqthonglor.com,0,NaN,[],true_negative_in_stored_snapshot,No matching structure was found in the stored ...,stored_cleaned_main_content_html_or_markdown
98,comparison,measured_negative,https://agent.in.th/read/buy-condo,https://agent.in.th/read/buy-condo?utm_source=...,agent.in.th,0,NaN,[],true_negative_in_stored_snapshot,No matching structure was found in the stored ...,stored_cleaned_main_content_html_or_markdown
99,comparison,measured_negative,https://agentplusth.com/en/detail/10634/lang-s...,https://www.agentplusth.com/en/detail/10634/la...,agentplusth.com,0,NaN,[],true_negative_in_stored_snapshot,No matching structure was found in the stored ...,stored_cleaned_main_content_html_or_markdown

                                              check  passed
0                     table: ratios between 0 and 1    True
1               table: absence is not position zero    True
2                     table: quartiles match ratios    True
3                        table: counts non-negative    True
4                      list: ratios between 0 and 1    True
5                list: absence is not position zero    True
6                      list: quartiles match ratios    True
7                         list: counts non-negative    True
8                       faq: ratios between 0 and 1    True
9                 faq: absence is not position zero    True
10                      faq: quartiles match ratios    True
11                         faq: counts non-negative    True
12            direct_answer: ratios between 0 and 1    True
13      direct_answer: absence is not position zero    True
14            direct_answer: quartiles match ratios    True
15               direct_answer: counts non-negative    True
16               definition: ratios between 0 and 1    True
17         definition: absence is not position zero    True
18               definition: quartiles match ratios    True
19                  definition: counts non-negative    True
20               comparison: ratios between 0 and 1    True
21         comparison: absence is not position zero    True
22               comparison: quartiles match ratios    True
23                  comparison: counts non-negative    True
24                    steps: ratios between 0 and 1    True
25              steps: absence is not position zero    True
26                    steps: quartiles match ratios    True
27                       steps: counts non-negative    True
28         numeric_evidence: ratios between 0 and 1    True
29   numeric_evidence: absence is not position zero    True
30         numeric_evidence: quartiles match ratios    True
31            numeric_evidence: counts non-negative    True
32        external_citation: ratios between 0 and 1    True
33  external_citation: absence is not position zero    True
34        external_citation: quartiles match ratios    True
35           external_citation: counts non-negative    True
36         question_heading: ratios between 0 and 1    True
37   question_heading: absence is not position zero    True
38         question_heading: quartiles match ratios    True
39            question_heading: counts non-negative    True
40                       density denominators valid    True
41                extraction failure is not absence    True
42                         citation label preserved    True
43                              row total preserved    True

## 9. Model-readiness handoff

This is a recommendation table only. No new regression is estimated. Presence and position should remain separate in any later specification.

In [10]:
readiness = pd.read_csv(OUT / 'tables/position_feature_model_readiness.csv')
display(readiness)

,feature,recommended_representation,suggested_reference_group,full_sample_usable,conditional_sample_usable,domain_FE_usable,fixed_effect_readiness,sparse_cell_risk,multicollinearity_risk,recommended_model_role,reason
0,table,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,high,main model candidate,Coverage=15.8%; 33 domains vary in both positi...
1,list,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,high,main model candidate,Coverage=46.6%; 83 domains vary in both positi...
2,faq,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=13.3%; 32 domains vary in both positi...
3,direct_answer,"First quartile, middle half, last quartile",No feature for full sample; Q4 for feature-pre...,True,True,False,Weak within-domain variation,high,high,robustness check,Coverage=3.1%; 7 domains vary in both position...
4,definition,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=41.0%; 93 domains vary in both positi...
5,comparison,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=20.6%; 56 domains vary in both positi...
6,steps,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=14.0%; 46 domains vary in both positi...
7,numeric_evidence,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,high,main model candidate,Coverage=51.5%; 89 domains vary in both positi...
8,external_citation,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=29.8%; 74 domains vary in both positi...
9,question_heading,"Q1, Q2, Q3, Q4",No feature for full sample; Q4 for feature-pre...,True,True,True,Ready,low,moderate,position extension,Coverage=19.6%; 53 domains vary in both positi...

## 10. Evidence-based conclusion

The conclusion is generated directly from the validated diagnostics and is also exported as plain text for downstream review.

In [11]:
findings = (OUT / 'POSITION_FEATURE_EDA_FINDINGS.txt').read_text(encoding='utf-8')
print(findings)

POSITION FEATURE EDA FINDINGS

Scope
5,758 surfaced source-prompt rows; 2,881 unique URLs; 586 domains; citation rate 32.9%.

Coverage
Features with at least 10 percent eligible-page coverage: table, list, faq, definition, comparison, steps, numeric_evidence, external_citation, question_heading.

Descriptive citation differences
Largest absolute cited versus not-cited median-position differences: question_heading, list, table, external_citation, comparison. These are descriptive associations, not causal effects.

Domain fixed-effects readiness
Ready or usable with caution: table, list, faq, definition, comparison, steps, numeric_evidence, external_citation, question_heading.
Not suitable: none.

Future representation
Use the feature-specific grouping in position_feature_model_readiness.csv. No-feature and position effects must remain separate. Sparse groups must not be merged silently.

Future model role
Main-model candidates: table, list, numeric_evidence.
Position extensions: faq, definition, comparison, steps, external_citation, question_heading.
Robustness checks: direct_answer.
Exclude: none.

Limitations
Position is measured from stored cleaned main-content HTML, with generated Markdown only when HTML is unavailable. Dynamic content, scrape-version drift, imperfect main-content selection, and template confounding remain. This pipeline does not fit a new LPM or logistic regression.